package cl.pymeflow.plan.model;

public enum Capacidad {

    CLIENTES,
    PROVEEDORES,
    PRODUCTOS,
    COMPRAS,
    VENTAS,
    INVENTARIO,
    GASTOS,

    DASHBOARD_BASICO,
    IVA_BASICO,

    MULTIUSUARIO,
    IVA_COMPLETO,
    EXPORTAR_PDF,
    EXPORTAR_EXCEL,
    INVENTARIO_AVANZADO,
    DASHBOARD_AVANZADO,
    REPORTES,
    DOCUMENTOS,

    MULTIBODEGA,
    API,
    AUDITORIA_AVANZADA,
    AUTOMATIZACIONES,
    IA,
    INTEGRACIONES,

    MERCADO_LIBRE
}